/******************************************************************************/
/***          Generated by IBExpert 2006.03.07 15/04/2011 23:39:08          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'localhost:D:\Desenvolvimento\OpenSource\dbunit4delphi\unittest\db\sample.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE PERSON (
    ID         INTEGER NOT NULL,
    NAME       VARCHAR(60),
    BIRTHDATE  DATE,
    SALARY     NUMERIC(15,2)
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE PERSON ADD CONSTRAINT PK_PERSON PRIMARY KEY (ID);
