CREATE TABLE DUAL (
    DUMMY  CHAR(1)
);


CREATE TABLE PERSON (
    ID         INTEGER NOT NULL,
    NAME       VARCHAR(60),
    BIRTHDATE  DATE,
    SALARY     NUMERIC(15,2)
);


INSERT INTO DUAL (DUMMY) VALUES ('X');

COMMIT WORK;

INSERT INTO PERSON (ID, NAME, BIRTHDATE, SALARY) VALUES (1, 'Fabricio', '1983-07-15', 1543.21);

COMMIT WORK;

ALTER TABLE PERSON ADD CONSTRAINT PK_PERSON PRIMARY KEY (ID);
